package converter

import (
	"os"
	"path/filepath"

	"github.com/caioreix/agency-cli/internal/agent"
)

type aider struct{}

func init() {
	Register("aider", &aider{})
}

func (c *aider) Name() string        { return "Aider" }
func (c *aider) Description() string  { return "CONVENTIONS.md (project-scoped)" }
func (c *aider) IsProjectScoped() bool { return true }

func (c *aider) Convert(a *agent.Agent, destDir string) ([]string, error) {
	if err := os.MkdirAll(destDir, 0o755); err != nil {
		return nil, err
	}

	outFile := filepath.Join(destDir, "CONVENTIONS.md")

	// Aider uses a single CONVENTIONS.md; append if exists
	entry := "\n---\n\n" +
		"## " + a.Name + "\n\n" +
		"> " + a.Description + "\n\n" +
		a.Body

	var content string
	if existing, err := os.ReadFile(outFile); err == nil {
		content = string(existing) + entry
	} else {
		header := "# The Agency — AI Agent Conventions\n" +
			"#\n" +
			"# This file provides Aider with specialized AI agents from The Agency.\n" +
			"# To activate an agent, reference it by name in your Aider session prompt.\n" +
			"#\n" +
			"# Generated by agency-cli — do not edit manually.\n"
		content = header + entry
	}

	if err := os.WriteFile(outFile, []byte(content), 0o644); err != nil {
		return nil, err
	}

	return []string{outFile}, nil
}
