package converter

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/caioreix/agency-cli/internal/agent"
)

type windsurf struct{}

func init() {
	Register("windsurf", &windsurf{})
}

func (c *windsurf) Name() string        { return "Windsurf" }
func (c *windsurf) Description() string  { return ".windsurfrules (project-scoped)" }
func (c *windsurf) IsProjectScoped() bool { return true }

func (c *windsurf) Convert(a *agent.Agent, destDir string) ([]string, error) {
	if err := os.MkdirAll(destDir, 0o755); err != nil {
		return nil, err
	}

	outFile := filepath.Join(destDir, ".windsurfrules")

	// Windsurf uses a single rules file; append if exists
	separator := strings.Repeat("=", 80)
	entry := "\n" + separator + "\n" +
		"## " + a.Name + "\n" +
		a.Description + "\n" +
		separator + "\n\n" +
		a.Body + "\n"

	var content string
	if existing, err := os.ReadFile(outFile); err == nil {
		content = string(existing) + entry
	} else {
		header := "# The Agency — AI Agent Rules for Windsurf\n" +
			"#\n" +
			"# Full roster of specialized AI agents from The Agency.\n" +
			"# To activate an agent, reference it by name in your Windsurf conversation.\n" +
			"#\n" +
			"# Generated by agency-cli — do not edit manually.\n"
		content = header + entry
	}

	if err := os.WriteFile(outFile, []byte(content), 0o644); err != nil {
		return nil, err
	}

	return []string{outFile}, nil
}
